ulti

diff --git a/.github/workflows/main_elite-web.yml b/.github/workflows/main_elite-web.yml
--- a/.github/workflows/main_elite-web.yml
+++ b/.github/workflows/main_elite-web.yml
@@ -1,8 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
-name: Build and deploy Node.js app to Azure Web App - elite-web
-
 on:
   push:
     branches:
@@ -13,8 +8,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
-
+      contents: read
     steps:
       - uses: actions/checkout@v4
 
@@ -29,8 +23,17 @@ jobs:
           npm run build --if-present
           npm run test --if-present
 
-      - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+      - name: List directory after build
+        run: ls -al
+
+      - name: Zip build artifact for deployment
+        run: |
+          if [ -d "dist" ]; then
+            zip -r release.zip dist
+          else
+            echo "Error: 'dist' folder not found. Please verify that the build step is generating the folder."
+            exit 1
+          fi
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -45,9 +48,8 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
-
+      id-token: write
+      contents: read
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
@@ -56,19 +58,18 @@ jobs:
 
       - name: Unzip artifact for deployment
         run: unzip release.zip
-      
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
-          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8A6B228BABE446E8D767A5D21EF650C }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F7F271CC340493FAC90F4778CC66827 }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AD0B1BBC76646A688D9B2A485F5777A }}
+          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EDB97552BFC4D7780822557289635F1 }}
+          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_773E356078F34D2B9C116FB529A1B19D }}
+          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F96DFE0488CD492AA7631A4033A7C219 }}
 
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
         with:
-          app-name: 'elite-web'
+          app-name: 'elite-app-web'
           slot-name: 'Production'
-          package: .
-          
+          package: ./dist 
